language: python
python:
- '2.7'
install:
- pip install ansible==2.4.0
- pip install jmespath
script:
- ansible-playbook tests/write-inventory-files.yml
- ansible-playbook -i tests/inventory tests/3scale-saas-with-hosted-apicast.yml
env:
  global:
    # travis encrypt "THREESCALE_INVENTORY=$(yaml2json tests/3scale-inventory.yaml|base64)"
    secure: "TjqtVqGqWneStstIfqlTDRvPPEF7UXQbVaBvR9/g7zDZuEyzui781I3jLlv8M72omLp1yUkEorAjbmBd7So2kIaS5kl9MkqyEaG5JonPMbhBxyos47hyQlKQ9OB31UZZaQFmurOamO/aa22zEw1w3sfjqKqn+U1fYxtEg3262TMjYx3rbgRhqNYEN35hO1VpUw6elRddyrirCTV66nyfE7GQ/PIhejnruPolCGVo/h+WInIBhEz5/BUb2vRCtGn5OhHH+WdIvAp8W2adB55hRfenPTSg7qQnrCyPFgSXkeFUL0H0xc6J/n2+cch9oDRzHoANyTeb0rmdbN/bvGN3bLrojYLGuZbIK6cjmpo14wJmUaPmxzL91z/IHszAqz5f1PlfGz2J+KVcoJf4R3/91ReuQFYClrz8Wf/RlSV2yqkknk34aCr03TWhSENwVRoP1pcO96emGC2mmX+Br0DzCLK9HWsyk1yQfC4YzxU0tjqYshLLcW5olxa7kU0Wn2L3Ju+F8pTnkKCSEsdHLDGKTHlzhQVhq1gvhspC2LZGr+3zyU5vCQ53PxUNusGzRRRMbNKr/VOB1xc/+CabRUGM42GZKKCz7wGkZPmPfeMe7NCcyRPvAQSP3PupQB+PbgOgOfC8vhHXGViPix7cd2WSwLTJ1yT1jgxBvjP7TTnRS1k="
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
