---

- include_tasks: api-calls/update_application_plan.yml
  when: 'threescale_cicd_application_plan.system_name in threescale_cicd_existing_application_plans'

- include_tasks: api-calls/create_application_plan.yml
  when: 'threescale_cicd_application_plan.system_name not in threescale_cicd_existing_application_plans'

