---

- name: Retrieve existing metrics from the 3scale Admin Portal
  uri:
    url: "{{ service_url }}/metrics.json?access_token={{ threescale_cicd_access_token|urlencode }}"
    validate_certs: no
  register: threescale_cicd_tmpresponse
  no_log: '{{ threescale_cicd_nolog }}'
  vars:
    service_url: https://{{ inventory_hostname }}/admin/api/services/{{ threescale_cicd_api_service_id }}

- name: Set the list of existing metrics as facts
  set_fact:
    threescale_cicd_existing_metrics: >-
      {{ threescale_cicd_tmpresponse.json|json_query('metrics[*].metric.system_name') }}
    threescale_cicd_existing_metrics_details: >-
      {{ threescale_cicd_tmpresponse.json|json_query('metrics[].{"system_name": metric.system_name, "id": metric.id}') }}

- include_tasks: "steps/method.yml"
  with_dict: '{{ threescale_cicd_api_operations }}'
  loop_control:
    loop_var: threescale_cicd_api_operation
