---

- name: Abort on deprecated feature -> the "sso" inventory group
  fail:
    msg: >-
      You are currently using a deprecated feature (the 'sso' group in your inventory).
      Please replace it with the 'threescale_cicd_sso_issuer_endpoint' variable.
      Alternatively, you can also bypass this warning by setting the 'threescale_cicd_deprecated_features'
      extra variable to 'true'.
  when: >-
    threescale_cicd_sso_issuer_endpoint|default("")|length > 0 and 'sso' in groups
    and groups['sso'] > 0 and threescale_cicd_api_backend_version == 'oidc'
    and not threescale_cicd_deprecated_features|default(false)|bool

- name: Abort on deprecated feature -> the "apicast-sandbox" inventory group
  fail:
    msg: >-
      You are currently using a deprecated feature (the 'apicast-sandbox' group in your inventory).
      Please replace it with the 'threescale_cicd_apicast_sandbox_endpoint' variable.
      Alternatively, you can also bypass this warning by setting the 'threescale_cicd_deprecated_features'
      extra variable to 'true'.
  when: >-
    threescale_cicd_apicast_sandbox_endpoint|default("")|length > 0 and 'apicast-sandbox' in groups
    and groups['apicast-sandbox'] > 0 and not threescale_cicd_deprecated_features|default(false)|bool

- name: Abort on deprecated feature -> the "apicast-production" inventory group
  fail:
    msg: >-
      You are currently using a deprecated feature (the 'apicast-production' group in your inventory).
      Please replace it with the 'threescale_cicd_apicast_production_endpoint' variable.
      Alternatively, you can also bypass this warning by setting the 'threescale_cicd_deprecated_features'
      extra variable to 'true'.
  when: >-
    threescale_cicd_apicast_production_endpoint|default("")|length > 0 and 'apicast-production' in groups
    and groups['apicast-production'] > 0 and not threescale_cicd_deprecated_features|default(false)|bool
