---

- debug:
    var: threescale_cicd_update_application_plan_payload
    verbosity: 1
  no_log: '{{ threescale_cicd_nolog }}'

- name: Update the application plan
  uri:
    url: '{{ service_url }}/application_plans/{{ application_plan_id }}.json'
    validate_certs: no
    method: PUT
    body: '{{ threescale_cicd_update_application_plan_payload }}'
    status_code: 200
  register: threescale_cicd_tmpresponse
  changed_when: 'threescale_cicd_tmpresponse.status == 200'
  no_log: '{{ threescale_cicd_nolog }}'
  vars:
    service_url: https://{{ inventory_hostname }}/admin/api/services/{{ threescale_cicd_api_service_id }}
    application_plan_id: >-
      {{ (threescale_cicd_existing_application_plans_details|selectattr("system_name", "equalto", threescale_cicd_application_plan.system_name)|first).id }}

- name: Wait for a couple seconds
  pause:
    seconds: '{{ threescale_cicd_throttling }}'
