---

- debug:
    var: threescale_cicd_update_activedoc_payload
    verbosity: 1

- name: Update the ActiveDocs
  uri:
    url: 'https://{{ inventory_hostname }}/admin/api/active_docs/{{ threescale_cicd_api_activedocs_id }}.json'
    validate_certs: no
    method: PUT
    body: '{{ threescale_cicd_update_activedoc_payload }}'
    status_code: 200
  register: threescale_cicd_tmpresponse
  changed_when: 'threescale_cicd_tmpresponse.status == 200'

- name: Wait for a couple seconds
  pause:
    seconds: '{{ threescale_cicd_throttling }}'
