---

- debug:
    var: threescale_cicd_update_service_payload
    verbosity: 1
  no_log: '{{ threescale_cicd_nolog }}'

- name: Update the service
  uri:
    url: https://{{ inventory_hostname }}/admin/api/services/{{ threescale_cicd_api_service_id }}.json
    validate_certs: no
    method: PUT
    body: '{{ threescale_cicd_update_service_payload }}'
    status_code: 200
  register: threescale_cicd_tmpresponse
  changed_when: 'threescale_cicd_tmpresponse.status == 200'
  no_log: '{{ threescale_cicd_nolog }}'

- name: Wait for a couple seconds
  pause:
    seconds: '{{ threescale_cicd_throttling }}'
